### ISSUE TITLE
Unable to edit Content Type with ezselection and sckenhancedselection in eZ Platform 2.5.1

### ISSUE THREAD

**Issue by SerheyDolgushev** [netgen/NetgenEnhancedSelectionBundle#26]
Steps to reproduce:
1. Install eZ Platform 2.5.1.
2. Install and enable `enhanced-selection-bundle`:`3.1.0`.
3. Create new Content Type and add both Field Types there:
    - `ezselection`
    - `sckenhancedselection`
4. Save the Content Type.
5. Try to edit previously created Content Type.

**Expected Result**: content type edit form.
**Actual Result**: exception is thrown:
```
Unable to render the form as none of the following blocks exist: "_ezrepoforms_contenttype_update_fieldDefinitionsData_entry_options_entry_widget", "text_widget", "form_widget".
```

This one is very strange. After spending a lot of time on this, we ended up with a workaround:
1. Override `ezselection_field_definition_edit` block in the `AppBundle`.
2. Remove `{{ form_errors(option) }}` line in the overridden `ezselection_field_definition_edit` block.

Pretty sure there should be a more proper fix.

**Comment by emodric** [comment]
Hi @SerheyDolgushev 

I have tested this on eZ Platform 2.5.2 and I cannot reproduce the issue.

Have you tried this on a clean install?

**Comment by SerheyDolgushev** [comment]
@emodricI  tested `enhanced-selection-bundle` (`3.1.0` and `3.2.0`) on eZ Platform `2.5.2` and also wasn't able to reproduce the issue. So seems like it was something eZ Platform `2.5.1` related.

**Comment by emodric** [comment]
Should we close this then?

**Comment by SerheyDolgushev** [comment]
Yep :)
