### ISSUE TITLE
No empty option available

### ISSUE THREAD

**Issue by kossuth-wt** [netgen/NetgenEnhancedSelectionBundle#29]
The is no possibility to add an empty option.

A possible solution is to add an empty option by default if the field is not required based on the field definition. Currently if the field is not required there is no empty option and the first option is selected by default when I create a content having this field type.

**Comment by emodric** [comment]
It is now (in next minor release) possible to add an empty option with an empty identifier. Only one such option is possible and it can be placed in any position.
