### ISSUE TITLE
jQuery problem

### ISSUE THREAD

**Issue by GFournie** [netgen/NetgenEnhancedSelectionBundle#36]
Hi,

We have a problem with Netgen Enhanced Selection Bundle in AdminUI (Ibexa 4.6.12/ netgen bundle 5.2.2).
We can't remove an option.
And we can't neither add an option (clicking AddOption button closes the form and returns to the view type page).

It seems that jQuery is not loaded.

```
Uncaught ReferenceError: jQuery is not defined

      <anonymous> https://.../bundles/netgenenhancedselection/admin/js/multientry.js:128  Uncaught ReferenceError: jQuery is not defined
      <anonymous> https://.../bundles/netgenenhancedselection/admin/js/init.js:41
```

I added autoProvidejQuery in ibexa.webpack.config.js

```
module.exports = (Encore) => {
   Encore.setOutputPath('public/assets/ibexa/build')
    .setPublicPath('/assets/ibexa/build')
    .addExternals({
      react: 'React',
      'react-dom': 'ReactDOM',
      moment: 'moment',
      'popper.js': 'Popper',
      alloyeditor: 'AlloyEditor',
      'prop-types': 'PropTypes',
    })
    .enableSassLoader()
    .enableReactPreset()
    .autoProvidejQuery()
    .enableSingleRuntimeChunk();
```    

I ran php bin/console ibexa:encore:compile -c ibexa

I cleared the cache

I installed jQuery in nodeJS (not sure if it was needed)

But the problem remains.
Thanks for your help.

**Comment by hknezevic** [comment]
Hi @GFournie ,
thank you for reporting the issue. We were able to reproduce it.
A support ticket has been created, and we will address this issue beginning of the next week.

Cheers,
Hrvoje

**Comment by emodric** [comment]
@hknezevic @GFournie I just wanted to add that we are looking into rewriting the JavaScript to vanilla.

**Comment by GFournie** [comment]
Thanks.

Also, thank you for this very useful bundle :-)

**Comment by hknezevic** [comment]
@GFournie new release is out: 
https://github.com/netgen/NetgenEnhancedSelectionBundle/tree/5.3.0
https://packagist.org/packages/netgen/enhanced-selection-bundle#5.3.0
(thx for the fix @amalija-ramljak)

Jquery dependency has been completely removed, and the field type edit interface should now work as expected. So please update the bundle to the latest version, and your problem should be resolved.

Cheers,
Hrvoje

**Comment by GFournie** [comment]
Thanks. I updated it and I have a few problems...

* When updating, I get at the end of the process : 
Executing script ibexa:encore:compile --config-name app [KO]
 [KO]
Script ibexa:encore:compile --config-name app returned with error code 1
!!  Compiling all prod assets.
!!
!!    RUN  Evaluating command yarn encore prod --config-name app
!!
!!    OUT  yarn run v1.22.22
!!    OUT  $ /www/ezpublish.cirad.fr/trav/4.6.12/node_modules/.bin/encore prod --config-name app
!!    OUT  Running webpack ...
!!    OUT
!!    OUT
!!    ERR  [webpack-cli] Configuration with the name "app" was not found.
!!    ERR  error Command failed with exit code 2.

* But it seems to work as I can add new options... but not quite : 
    * I can add and remove new options
    * But I can't remove an already existing option
    * And when I save the type I get an error : The name "Thu Nov 07 2024 13:01:55 GMT+0100 (heure normale d’Europe centrale)0" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":"). [in vendor/symfony/form/FormConfigBuilder.php:793]

Is there something odd in my installation ?

Thanks

**Comment by emodric** [comment]
`Configuration with the name "app" was not found` error does not come from EnhancedSelection bundle. We do not plug into the build process in this bundle.

As for the other errors, @amalija-ramljak, can you take a look, please?

**Comment by GFournie** [comment]
I just installed the bundle on a fresh Ibexa 4.6.13 version and I don't get the "Configuration app errror"...
Sorry for that.

**Comment by hknezevic** [comment]
I don't think the rest of the errors are also related to our bundle, as the scripts for the Enhanced selection bundle are included in the admin layout body as a twig component:

```
 netgen.enhanced_selection.ibexa.admin.component.javascripts:
    parent: Ibexa\AdminUi\Component\TwigComponent
        arguments:
             - "@twig"
             - "@@NetgenEnhancedSelection/ibexa/admin/javascripts.html.twig"
         tags:
             - { name: ibexa.admin_ui.component, group: 'script-body' }
```

 
so they are not added in the webpack build and should not affect assets build in any way. Just make sure to run the assets:install public (--symlink --relative) command, so the scripts are properly made available in the public folder. If you haven't used --symlink parameter, then you definitely need to run the script again to overwrite the old file versions.

**Comment by emodric** [comment]
@hknezevic Do you mean these errors?

```
But I can't remove an already existing option

And when I save the type I get an error : The name "Thu Nov 07 2024 13:01:55 GMT+0100
(heure normale d’Europe centrale)0" contains illegal characters. Names should start with
a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"),
hyphens ("-") and colons (":"). [in vendor/symfony/form/FormConfigBuilder.php:793]
```

Those do indeed sound like issues in the new implementation.

**Comment by GFournie** [comment]
OK. Thanks for all !
I'll try to move our application to the fresh 4.6.13 to see it is solves some of the problems.

**Comment by hknezevic** [comment]
> @hknezevic Do you mean these errors?
> 
> ```
> But I can't remove an already existing option
> 
> And when I save the type I get an error : The name "Thu Nov 07 2024 13:01:55 GMT+0100
> (heure normale d’Europe centrale)0" contains illegal characters. Names should start with
> a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"),
> hyphens ("-") and colons (":"). [in vendor/symfony/form/FormConfigBuilder.php:793]
> ```
> 
> Those do indeed sound like issues in the new implementation.

Ah, I missed that part, sorry. Yeah, but this looks unrelated to the latest release. Perhaps when we build the form in the backend, we pass a field name value somewhere which is not properly cleaned from special characters and ascii transformed.

In fact, I am not sure if it is even related to enhanced selection field type. Just look at the name the error is reporting:
"Thu Nov 07 2024 13:01:55 GMT+0100 (heure normale d’Europe centrale)0"
This is a formatted date value. And I even tried adding that value as the field name, and as an option name, and nothing broke, so I assume this does not relate to enhanced selection content field form in the content type.

**Comment by hknezevic** [comment]
Aha, found it. After adding first option (with index 0), every newly added option adds formatted date as a part of the field name, instead of timestamp (which is used to distinct the newly created options on submit)

```
<input type="text" id="ezplatform_content_forms_contenttype_update_fieldDefinitionsData_content_field_672cb3e7d1038_options_Thu Nov 07 2024 13:53:33 GMT+0100 (Central European Standard Time)0_name" name="ezplatform_content_forms_contenttype_update[fieldDefinitionsData][content][field_672cb3e7d1038][options][Thu Nov 07 2024 13:53:33 GMT+0100 (Central European Standard Time)0][name]" required="required" class="ibexa-input ibexa-input--text form-control" placeholder=" ">
```

**Comment by hknezevic** [comment]
@GFournie I have released a patch
https://packagist.org/packages/netgen/enhanced-selection-bundle#5.3.1

Can you try now? The error with the form field name should now be fixed, and removing options should now also be functional

**Comment by GFournie** [comment]
@hknezevic  I confirm that all is working well !

Thanks to all your team !

**Comment by emodric** [comment]
Thanks for the report and testing @GFournie !
