### ISSUE TITLE
Missing field type name in eZ Platform

### ISSUE THREAD

**Issue by nmeirik** [netgen/NetgenEnhancedSelectionBundle#6]
When selecting the field type from the Field type selection dropdown, the name appears as `sckenhencedselection.name`

**Comment by emodric** [comment]
What needs to be done do display it correctly?

My colleague says in his blog post (http://www.netgenlabs.com/Blog/Adding-support-for-a-new-field-type-to-eZ-Publish-Platform-UI), that adding something like this:

`sckenhancedselection: { name: "Enhanced selection" }`

to `Resources/translations/fieldtypes.en.yml`

Can you test and I will gladly fix it ( or you can create the PR :) )

**Comment by nmeirik** [comment]
I'll give this another go if https://github.com/netgen/NetgenEnhancedSelectionBundle/issues/7 can be resolved.
