### ISSUE TITLE
Support for eZ Platform (without legacy)

### ISSUE THREAD

**Issue by nmeirik** [netgen/NetgenEnhancedSelectionBundle#7]
It would be great if this bundle could support a clean installation of eZ Platform (without the need for legacy).

**Comment by emodric** [comment]
Is removing the legacy extension from composer `require` section enough?

**Comment by nmeirik** [comment]
According to the README file:

> However, The eZ Publish 4 extension is still required to populate field type through the admin interface

...so I guess not. Populating the field type in eZ Platform would be a requirement for it to not need legacy.

**Comment by emodric** [comment]
I hardly have time to implement Platform UI support myself, so it will have to wait a bit, but PRs are welcome :)

**Comment by nmeirik** [comment]
I understand. Do you know if there exists any documentation yet on how to extend the eZ Platform backend UI?

**Comment by emodric** [comment]
My colleague wrote about it some time ago: http://www.netgenlabs.com/Blog/Adding-support-for-a-new-field-type-to-eZ-Publish-Platform-UI

**Comment by nmeirik** [comment]
Thanks for the tip! I'll create an internal issue for this in our systems, and hopefully we'll be able to get to it in a reasonable amount of time. ;)

**Comment by nmeirik** [comment]
I belive the following also might be related to this issue:

When installing this bundle via composer an `extension` folder is created in the root directory of eZ Platform, into which the directories `enhancedselection2` and `eztags` are created. This appears to be eZ Publish legacy extensions.

**Comment by emodric** [comment]
@nmeirik I believe that should be fixed when `enhancedselection2` is removed from `require` section.

As for `eztags`, Tags Bundle is probably "guilty" for that.

I will tag v2.1 of Tags Bundle that does not require legacy extension, but it also does not have Platform UI interface.

**Comment by TFohrer** [comment]
@emodric Any news on this issue ? I'm currently trying to install this bundle on ez studio and I can add a field with the type "Enhanced Selection", but I can't add any options for the selection. 

![bildschirmfoto 2016-10-06 um 16 34 44](https://cloud.githubusercontent.com/assets/5895734/19156616/d77b4408-8be2-11e6-86f2-deb2ba3874c5.png)

**Comment by emodric** [comment]
@TFohrer Unfortunatelly not. We don't have time nor resources to tackle Platform UI integration at this point.

**Comment by emodric** [comment]
Pull requests are however accepted :)

**Comment by emodric** [comment]
Implemented as of 3.1.0.
